### ISSUE TITLE
希望有空上传一下后端怎么获取空教室的代码

### ISSUE THREAD

**Issue by GuangDai** [Jraaay/empty-classroom-public#1]
（垃圾教务，我按照现在仓库的代码无法获取了

**Comment by Jraaay** [comment]
后端获取教务空教室数据的方法没变捏，注意一下要用encoded_pwd
可以通过在这里登录然后抓个包看看编码后的pwd是啥直接填进去就行：
http://jwglweixin.bupt.edu.cn/sjd/#/login
然后还获取不到估计是教务抽风…线上目前是做了fallback到课表的兜底，如果你需要的话可以参考这种方式或者多重试下

**Comment by GuangDai** [comment]
教务已经抽风两天了，现在login不上去，打开这个页面给我报错服务器错误。
之所以选择这个网页是因为他似乎是能知道哪个教室被一些班级预约开会了，比教务系统的班级课表有这个优势
